# -*- coding: utf-8 -*-
"""bone_marrow.ipynb adlı dosyanın kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DUvK-sZDUE6orGLqbRAfocwhDUQoqoU
"""

!pip install scanpy

!pip install anndata

!pip3 install igraph

!pip install celltypist

!pip install decoupler

!pip install fa2-modified

"""**Import core single cell tools**

"""

import scanpy as sc
import anndata as ad

"""**Load Data**"""

from google.colab import files
uploaded = files.upload()

!ls

adata = sc.read("bone_marrow.h5ad")

print(adata)

adata.shape

adata.var.head()

adata.obs.head()

adata.to_df()

"""**QUALITY CONTROL**

"""

adata.var_names_make_unique()
adata.obs_names_make_unique()

adata.obs.head()

adata.var.head()

adata.var["mt"] = adata.var_names.str.startswith("MT-")
sc.pp.calculate_qc_metrics(adata, qc_vars=["mt"], percent_top=None, inplace=True)
adata.obs.head()

adata.var['RIBO'] = adata.var_names.str.startswith("RPS", "RPL")
adata.var['HB'] = adata.var_names.str.startswith("^HB[^(P)]")

"""**QUALITY CONTROL FILTERING**

"""

adata = adata[adata.obs.n_genes_by_counts < 4000, :]
adata = adata[adata.obs.n_genes_by_counts > 300, :]
adata = adata[adata.obs.pct_counts_mt < 10, :]
adata.obs.head()

"""**NORMALIZATION AND LOG TRANSFORMATION**"""

sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

"""**Identify highly variable genes (HVGs)**"""

sc.pp.highly_variable_genes(adata, n_top_genes=1000)

sc.pl.highly_variable_genes(adata )

sc.pp.highly_variable_genes(adata, min_mean=0.0125, max_mean=3, min_disp=0.5)
adata = adata[:, adata.var.highly_variable]
adata.var.head()

"""**Scale and regress out confounders**"""

sc.pp.scale(adata, max_value=10)

"""**PCA**"""

sc.tl.pca(adata)

sc.pl.pca_variance_ratio(adata, log=True)

""" **Compute neighborhood graph**"""

sc.pp.neighbors(adata)

"""**UMAP embedding for visualization**

"""

sc.tl.umap(adata)
sc.pl.umap(adata, color=["n_genes_by_counts", "pct_counts_mt"])

"""**Leiden clustering**"""

sc.tl.leiden(adata, resolution=0.5)
sc.pl.umap(adata, color=["leiden"])

"""**Find marker genes for each cluster**"""

sc.tl.rank_genes_groups(adata, "leiden", method="wilcoxon")
sc.pl.rank_genes_groups(adata, n_genes=20, sharey=False)

"""**Annotate clusters**"""

sc.get.rank_genes_groups_df(adata, group="0").head(20)

import pandas as pd
from scanpy import get
clusters = adata.obs['leiden'].cat.categories.tolist()
topn = 20

top_markers = {}
for cl in clusters:
    df = sc.get.rank_genes_groups_df(adata, group=cl)
    top_markers[cl] = df['names'].tolist()[:topn]


print("Top markers for cluster 0:", top_markers.get('0')[:10])
for cl, genes in top_markers.items():
    print(f"Cluster {cl} top genes:", genes[:8])

adata.var_names = [adata.var.loc[gene_id, 'gene_symbols'] if 'gene_symbols' in adata.var.columns else gene_id
                   for gene_id in adata.var_names]

print(adata.var_names[:10])

adata.obs['leiden'].value_counts()

cluster_cellgroup = pd.crosstab(adata.obs['leiden'], adata.obs['Cell.group'])
print(cluster_cellgroup)

cluster2celltype = adata.obs.groupby('leiden')['Cell.group'] \
                            .agg(lambda x: x.value_counts().idxmax()) \
                            .to_dict()

print(cluster2celltype)

adata.obs['cell_type'] = adata.obs['leiden'].map(cluster2celltype).astype('category')
sc.pl.umap(adata, color='cell_type', legend_loc='on data')

pd.crosstab(adata.obs['cell_type'], adata.obs['Cell.group'])